import { ROLE, MODULE, PERMISSION_ACTION } from '@/types/enums';
import type { Role, ModuleName, PermissionAction } from '@/types/enums';

/**
 * Mock permission matrix mapping each role to its module-level access.
 * ADMIN gets full access to everything — handled as a special case.
 */
const PERMISSION_MATRIX: Record<string, Record<string, PermissionAction>> = {
  [ROLE.BUSINESS_OWNER]: {
    [MODULE.PRODUCTS]: PERMISSION_ACTION.ADMIN,
    [MODULE.SALES_ORDERS]: PERMISSION_ACTION.VIEW,
    [MODULE.PURCHASE_ORDERS]: PERMISSION_ACTION.VIEW,
    [MODULE.MANUFACTURING_ORDERS]: PERMISSION_ACTION.VIEW,
    [MODULE.BOM]: PERMISSION_ACTION.VIEW,
    [MODULE.VENDORS]: PERMISSION_ACTION.VIEW,
    [MODULE.CUSTOMERS]: PERMISSION_ACTION.VIEW,
    [MODULE.INVENTORY]: PERMISSION_ACTION.VIEW,
    [MODULE.AUDIT_LOGS]: PERMISSION_ACTION.VIEW,
    [MODULE.USER_MANAGEMENT]: PERMISSION_ACTION.NONE,
    [MODULE.DASHBOARDS]: PERMISSION_ACTION.VIEW,
    [MODULE.PROCUREMENT]: PERMISSION_ACTION.VIEW,
    [MODULE.ANALYTICS]: PERMISSION_ACTION.VIEW,
  },
  [ROLE.SALES_USER]: {
    [MODULE.PRODUCTS]: PERMISSION_ACTION.VIEW,
    [MODULE.SALES_ORDERS]: PERMISSION_ACTION.ADMIN,
    [MODULE.PURCHASE_ORDERS]: PERMISSION_ACTION.NONE,
    [MODULE.MANUFACTURING_ORDERS]: PERMISSION_ACTION.NONE,
    [MODULE.BOM]: PERMISSION_ACTION.NONE,
    [MODULE.VENDORS]: PERMISSION_ACTION.NONE,
    [MODULE.CUSTOMERS]: PERMISSION_ACTION.ADMIN,
    [MODULE.INVENTORY]: PERMISSION_ACTION.VIEW,
    [MODULE.AUDIT_LOGS]: PERMISSION_ACTION.NONE,
    [MODULE.USER_MANAGEMENT]: PERMISSION_ACTION.NONE,
    [MODULE.DASHBOARDS]: PERMISSION_ACTION.VIEW,
    [MODULE.PROCUREMENT]: PERMISSION_ACTION.NONE,
    [MODULE.ANALYTICS]: PERMISSION_ACTION.VIEW,
  },
  [ROLE.PURCHASE_USER]: {
    [MODULE.PRODUCTS]: PERMISSION_ACTION.VIEW,
    [MODULE.SALES_ORDERS]: PERMISSION_ACTION.NONE,
    [MODULE.PURCHASE_ORDERS]: PERMISSION_ACTION.ADMIN,
    [MODULE.MANUFACTURING_ORDERS]: PERMISSION_ACTION.NONE,
    [MODULE.BOM]: PERMISSION_ACTION.VIEW,
    [MODULE.VENDORS]: PERMISSION_ACTION.ADMIN,
    [MODULE.CUSTOMERS]: PERMISSION_ACTION.NONE,
    [MODULE.INVENTORY]: PERMISSION_ACTION.VIEW,
    [MODULE.AUDIT_LOGS]: PERMISSION_ACTION.NONE,
    [MODULE.USER_MANAGEMENT]: PERMISSION_ACTION.NONE,
    [MODULE.DASHBOARDS]: PERMISSION_ACTION.VIEW,
    [MODULE.PROCUREMENT]: PERMISSION_ACTION.VIEW,
    [MODULE.ANALYTICS]: PERMISSION_ACTION.VIEW,
  },
  [ROLE.MANUFACTURING_USER]: {
    [MODULE.PRODUCTS]: PERMISSION_ACTION.VIEW,
    [MODULE.SALES_ORDERS]: PERMISSION_ACTION.NONE,
    [MODULE.PURCHASE_ORDERS]: PERMISSION_ACTION.NONE,
    [MODULE.MANUFACTURING_ORDERS]: PERMISSION_ACTION.ADMIN,
    [MODULE.BOM]: PERMISSION_ACTION.ADMIN,
    [MODULE.VENDORS]: PERMISSION_ACTION.NONE,
    [MODULE.CUSTOMERS]: PERMISSION_ACTION.NONE,
    [MODULE.INVENTORY]: PERMISSION_ACTION.VIEW,
    [MODULE.AUDIT_LOGS]: PERMISSION_ACTION.NONE,
    [MODULE.USER_MANAGEMENT]: PERMISSION_ACTION.NONE,
    [MODULE.DASHBOARDS]: PERMISSION_ACTION.VIEW,
    [MODULE.PROCUREMENT]: PERMISSION_ACTION.VIEW,
    [MODULE.ANALYTICS]: PERMISSION_ACTION.VIEW,
  },
  [ROLE.INVENTORY_MANAGER]: {
    [MODULE.PRODUCTS]: PERMISSION_ACTION.ADMIN,
    [MODULE.SALES_ORDERS]: PERMISSION_ACTION.VIEW,
    [MODULE.PURCHASE_ORDERS]: PERMISSION_ACTION.VIEW,
    [MODULE.MANUFACTURING_ORDERS]: PERMISSION_ACTION.VIEW,
    [MODULE.BOM]: PERMISSION_ACTION.VIEW,
    [MODULE.VENDORS]: PERMISSION_ACTION.VIEW,
    [MODULE.CUSTOMERS]: PERMISSION_ACTION.VIEW,
    [MODULE.INVENTORY]: PERMISSION_ACTION.ADMIN,
    [MODULE.AUDIT_LOGS]: PERMISSION_ACTION.VIEW,
    [MODULE.USER_MANAGEMENT]: PERMISSION_ACTION.NONE,
    [MODULE.DASHBOARDS]: PERMISSION_ACTION.VIEW,
    [MODULE.PROCUREMENT]: PERMISSION_ACTION.VIEW,
    [MODULE.ANALYTICS]: PERMISSION_ACTION.VIEW,
  },
};

/**
 * Check if a role has the required permission for a module.
 * ADMIN role always returns true (full access).
 */
export function hasPermission(
  role: Role | undefined,
  module: ModuleName,
  action: PermissionAction,
): boolean {
  if (!role) return false;
  if (role === ROLE.ADMIN) return true;

  const rolePerms = PERMISSION_MATRIX[role];
  if (!rolePerms) return false;

  const moduleAction = rolePerms[module];
  if (!moduleAction || moduleAction === PERMISSION_ACTION.NONE) return false;

  if (action === PERMISSION_ACTION.VIEW) {
    return moduleAction === PERMISSION_ACTION.VIEW || moduleAction === PERMISSION_ACTION.ADMIN;
  }
  if (action === PERMISSION_ACTION.ADMIN) {
    return moduleAction === PERMISSION_ACTION.ADMIN;
  }

  return false;
}
